
services:
  react-app:
    build:
      context: ./TopicHub-frontend
      dockerfile: Dockerfile
      args:
       - VITE_APP_BACKEND_ADDRESS=localhost:8080
    container_name: frontend-prod
    restart: always 
    
    ports:
      - '3000:3000'
    depends_on:
      - javaee-app


  javaee-app:
    build:
      context: ./TopicHub-backend
      dockerfile: Dockerfile
    container_name: backend-prod
    restart: always 
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DB_NAME: web_forum
      DB_USERNAME: postgres
      DB_PASSWORD: lhs22LI=D=
      DB_URL: jdbc:postgresql://db:5432/web_forum
      DB_DRIVER: org.postgresql.Driver
      FRONT: localhost

    

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: web_forum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lhs22LI=D=
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    
  migrations:
    image: redgate/flyway
    volumes:
      - ./TopicHub-backend/flyway:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/web_forum
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=lhs22LI=D=
      - FLYWAY_VALIDATE_MIGRATION_NAMING=true
    command: migrate
    depends_on:
      - db

volumes:
  db-data: null



    