
services:
  react-app:
    build:
      context: ./TopicHub-frontend
      dockerfile: Dockerfile
      args:
       - VITE_APP_BACKEND_ADDRESS=localhost:8080
    container_name: frontend-prod
    restart: always 
    
    ports:
      - '3000:3000'
    depends_on:
      - javaee-app

  javaee-app:
    build:
      context: ./TopicHub-backend
      dockerfile: Dockerfile
    container_name: backend-prod
    restart: always 
    ports:
      - '8080:8080'
    depends_on:
      - db
      - mc
    environment:
      DB_NAME: web_forum
      DB_USERNAME: postgres
      DB_PASSWORD: lhs22LI=D=
      DB_URL: jdbc:postgresql://db:5432/web_forum
      DB_DRIVER: org.postgresql.Driver
      MN_LOGIN: minioadmin
      MN_PASS: minioadmin
      MN_URL: http://192.168.0.5:9001
      MN_BUCKET: image
      CLIENT_HOST: localhost
      CLIENT_PORT: 3000
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: web_forum
      POSTGRES_USER:   postgres
      POSTGRES_PASSWORD:  lhs22LI=D=
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    
  migrations:
    image: redgate/flyway
    volumes:
      - ./TopicHub-backend/flyway:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/web_forum
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=lhs22LI=D=
      - FLYWAY_VALIDATE_MIGRATION_NAMING=true
    command: migrate
    depends_on:
      - db

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - "MINIO_ACCESS_KEY=minioadmin"
      - "MINIO_SECRET_KEY=minioadmin"
    ports:
      - "192.168.0.5:9001:9001" 
    volumes:
      - minio_data:/data  
    command: minio server /data

    restart: unless-stopped

  mc:
    image: minio/mc:latest  
    container_name: minio_client
    depends_on:
      - minio  
    entrypoint: >
      sh -c "
        sleep 10;
        mc alias set myminio http://minio:9001 minioadmin minioadmin;
        mc mb myminio/image; 
        mc ls minio 
      "
    restart: "no" 

volumes:
  db-data: null
  minio_data:
    driver: local



    
