
services:
  react-app:
    build:
      context: ./TopicHub-frontend
      dockerfile: Dockerfile
      args:
       - VITE_APP_BACKEND_ADDRESS=javaee-app
    container_name: frontend-prod
    restart: always 
    
    ports:
      - '3000:3000'
    depends_on:
      - javaee-app
    networks:
      - topichub

  javaee-app:
    build:
      context: ./TopicHub-backend
      dockerfile: Dockerfile
    container_name: backend-prod
    restart: always 
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DB_NAME: web_forum
      DB_USERNAME: postgres
      DB_PASSWORD: lhs22LI=D=
      DB_URL: jdbc:postgresql://db:5432/web_forum
      DB_DRIVER: org.postgresql.Driver
      FRONT: react-app
    networks:
      - topichub
    # entrypoint: >
    #   /bin/sh -c "curl -sSL https://github.com/vishnubob/wait-for-it/raw/master/wait-for-it.sh db:5432 -- java -jar /usr/local/tomcat/webapps/TopicHub-backend-1.0-SNAPSHOT.war

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: web_forum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lhs22LI=D=
    ports:
      - '5432:5432'
    networks:
      - topichub
    volumes:
      - db-data:/var/lib/postgresql/data
    
  migrations:
    image: redgate/flyway
    volumes:
      - ./TopicHub-backend/flyway:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/web_forum
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=lhs22LI=D=
      - FLYWAY_VALIDATE_MIGRATION_NAMING=true
    command: migrate
    depends_on:
      - db
    networks:
      - topichub
volumes:
  db-data: null

networks:
  topichub:
    driver: bridge

    